name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/node-web.yml
    with:
      lint-script: ""
      typecheck-script: ""
      build-script: ""
